---
asdf_version: "v0.8.1"
asdf_user: "{{ lookup('env', 'USER') }}"
asdf_user_home: "{{ lookup('env', 'HOME') }}"
asdf_legacy_version_file: "yes"
asdf_plugins:
  - name: "nodejs"
    repository: ""
    versions:
      - 14.0.0
    global: 14.0.0
